language: ruby
rvm:
  - 2.1
  - 2.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-2
jdk:
  - oraclejdk8
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
script: "CODECLIMATE_REPO_TOKEN=65d4787423f734f5cf6d2b3f9be88e481802e50af0879e8ed66971f972d70894 bundle exec rake"
